### PR TITLE
feat(diff): add diff for base64 values

### PR DESCRIPTION
**Pull request by gordonbondon**
This will try to check if values is base64 encoded and print pretty diff for it instead of a wall of symbols.
Before:
screenshot 2019-02-19 at 16 54 56

After:
screenshot 2019-02-19 at 16 55 13

### CODE REVIEW

**Comment by dmlittle** [comment]
@gordonbondon this is a pretty cool idea! 

I think there might be a chance where this change actually breaks sometimes. Base64 encoded data might contain actual human readable content like in the example that you showed but it can also contain random data (from something like `/dev/random`). If the data is random, the diff displayed won't actually work. I think we might be able to use some sort of entropy calculations to try to distinguish if the data is random or not and display the appropriate diff (base64 encoded or not respectively). 

I can look into different entropy calculations we can use and post an update on this PR. I believe we might be able to use something like the shannon entropy used in [truffleHog](https://github.com/dxa4481/truffleHog).

**Comment by dmlittle** [comment]
@gordonbondon thinking about this issue a little bit more I don't think we can use entropy and entropy differences or similarity between the two strings to figure out if we want to display the encoded or decoded representation or not. There are cases where the strings might be completely different but we still want to represent the base64 decoded contents.

I _think_ we might be able to just make a decision based on whether the base64 decoded strings contain non-ASCII characters or not. If the decoded strings only contain ASCII characters we can display the decoded versions. If there are any non-ASCII characters we will keep the base64 encoded diff.

Do you think you have time to try this? If you don't have time I'm happy to do the necessary changes and get this PR merged. Let me know!

The changes would looking like the following:
```go
func isASCII(s string) bool {
    for i := 0; i < len(s); i++ {
        if s[i] > unicode.MaxASCII {
            return false
        }
    }
    return true
}
```
```go
if isBeforeBase64 && isAfterBase64 && isASCII(oldString) && isASCII(newString) {
  // ...
}
```

**Comment by gordonbondon** [comment]
@dmlittle this sounds really good. I'll check it out.

**Comment by dmlittle** [comment]
@gordonbondon let me know if you want help getting this PR merged. I'm happy to help get this PR into a state it can be merged 😄

**Comment by gordonbondon** [comment]
@dmlittle 	Hi! Sorry, i decided to add some test for this case and it took some time : )


<details><summary>Test before adding ascii check:</summary>
<p>

```
→ make test
---> Testing
go test ./... -coverprofile coverage.out
?   	github.com/dmlittle/scenery	[no test files]
?   	github.com/dmlittle/scenery/pkg/cmd	[no test files]
ok  	github.com/dmlittle/scenery/pkg/parser	0.030s	coverage: 83.1% of statements
--- FAIL: TestPrintPlan (0.00s)
    printer_test.go:39:
        	Error Trace:	printer_test.go:39
        	Error:      	Not equal:
        	            	expected: "~ aws_instance.example\n    userd_data_hash:  \"e32a558d4e72c9157173e8b0f9e64f4ec59b6e857b79b2a5e71084fe6f4f1dbd\" => \"c37647d0ba0c466d9f36039dea07426394f74d76a739f55e904d3e5c31abdfc4\" \n    user_data_base64:  #! /bin/bash\n                       \n                      -echo \"foo\"\n                      +echo \"bar\"\n                       \n                      \n\n"
        	            	actual  : "~ aws_instance.example\n    userd_data_hash:  -{}\x9a\xe7\x9f\x1d\xe1\xee\xf6s\xddy\xef^\xf7{\xc6\xf4\u007f\u05fa\xe1\xfe\x1es\x9f[\xe9\xef9\xed\xbe\xfdof\xb9{\xbdt\xf3\x87\xde\xe9\xfe\x1f\xd5\xd6\xdd\n                      +s~\xfa\xe3\xb7tm\xad\x1c㮝\xf5\xfd\xfa\xd3\u007f]y\xad;\xe3n\xb7\xf7\x87\xfb\xe1\xde\xfak\xbd\xfd\u007f\x9e^\xf7N\x1d\xdd\xee\\\xdfV\x9bu\xf78\n                      \n    user_data_base64:  #! /bin/bash\n                       \n                      -echo \"foo\"\n                      +echo \"bar\"\n                       \n                      \n\n"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,5 @@
        	            	 ~ aws_instance.example
        	            	-    userd_data_hash:  "e32a558d4e72c9157173e8b0f9e64f4ec59b6e857b79b2a5e71084fe6f4f1dbd" => "c37647d0ba0c466d9f36039dea07426394f74d76a739f55e904d3e5c31abdfc4"
        	            	+    userd_data_hash:  -{}�����s�y�^�{��׺��s�[��9��of�{�t�������
        	            	+                      +s~��tm�㮝����]y�;�n������k���^�N��\�V�u�8
        	            	+
        	            	     user_data_base64:  #! /bin/bash
        	Test:       	TestPrintPlan
FAIL
coverage: 54.7% of statements
FAIL	github.com/dmlittle/scenery/pkg/printer	0.018s
make: *** [test] Error 1
```

</p>
</details>

<details><summary>After</summary>
<p>

```
→ make test
---> Testing
go test ./... -coverprofile coverage.out
?   	github.com/dmlittle/scenery	[no test files]
?   	github.com/dmlittle/scenery/pkg/cmd	[no test files]
ok  	github.com/dmlittle/scenery/pkg/parser	0.029s	coverage: 83.1% of statements
ok  	github.com/dmlittle/scenery/pkg/printer	0.017s	coverage: 66.7% of statements
```

</p>
</details>

**Comment by dmlittle** [comment]
@gordonbondon thanks for the PR sorry I haven't gotten around to review it yet. I'll try to look over it later today or tomorrow!

**Pull request merged**
