### PR TITLE
fix(parser): allow hyphen in attribute keys

### PR DESCRIPTION
**Pull request by gordonbondon**
Same as #14  but for `-`

### CODE REVIEW

**Comment by gordonbondon** [comment]
@dmlittle could you cut a release with this change?

**Comment by dmlittle** [comment]
@gordonbondon the v0.1.2 release is now available!

**Comment by gordonbondon** [comment]
@dmlittle hey, just noticed that scenery is for some reason released as `chamber`
screenshot 2019-02-26 at 12 22 54

**Comment by dmlittle** [comment]
@gordonbondon I was trying a new release script I wrote based of chamber and it looks like I forgot to rename the output binary name (the actual binary was still scenery). Regardless, that is now fixed. Thanks for reporting it!

**Pull request merged**
