### PR TITLE
Added scenery brew formula

### PR DESCRIPTION
**Pull request by okgolove**

### CODE REVIEW

**Comment by dmlittle** [comment]
@okgolove thanks for the PR! I'd love to have scenery distributed through Homebrew. This PR is more suited for [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) rather than this repo as that's where brew pulls from. Adding the formulae to this repo won't make it available through brew.  

I haven't added a brew formulae myself since it's [frowned upon to have authors submit their own tools](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) but if you have any issues with submitting the formulae I'm happy to help address them or help with tests.

**Comment by okgolove** [comment]
@dmlittle hey! I agree with you about Homebrew.
I tried to run `homebrew audit` for this formula and got some errors (that's why I pushed it here, instead of homebre-core repo). 2 errors were about repo's age and stars/forks count. And there is an error about dependency system:
```C: 12: col 5: Do not use `go get`. Please ask upstream to implement Go vendoring```

In this case, if you implement vendoring, it will be great. And then I will push this formula to homebrew-core.

**Comment by okgolove** [comment]
@dmlittle works fine! `brew audit --new-formula` said only "a repository is too new".
Do you want me to create a PR to homebrew-core with this formula, don't you?

**Comment by dmlittle** [comment]
@okgolove given that they don't want authors to submit their own tools I won't be submitting the formula myself. If you'd like to submit it, that'd be great (but please don't feel compelled to do so)! 

Otherwise, anyone who'd like to submit scenery's formula to brew is welcome to use the one I posted in the comments above (https://github.com/dmlittle/scenery/pull/10#issuecomment-456184447)

**Comment by dmlittle** [comment]
@okgolove thanks for trying! I'm going to close this PR for now and try to revisit the issue once this repo is older than 30 days. If that still doesn't work I might create a personal tap users can install scenery from.

**Pull request closed without merging**
